[tox]
requires =
    tox>=4.22
env_list = py{310,311,312,313,314}

[testenv]
description = run unit tests
dependency_groups =
    test
install_command =
    python -I -m pip install --only-binary=:all: {opts} {packages}
ignore_errors = True
ignore_outcome = True
commands = pytest
